import os
#os.rename('xyz.txt','abc.rtf')
f=open('abc.rtf')
print(*f)
print('this directory',os.getcwd())
#os.mkdir('fulder')
print('this dirrectory avdkdfh',os.getcwd())
#os.chdir('fulder')
#os.chdir('..')
#os.makedirs('nested1/nested2/nested3')
#os.makedirs('nested1/nested6')
#os.remove('fulder/qu.rtf')
#os.rmdir('fulder')
#os.removedirs('nested1/nested6')